---
- name: setup docker, jdk on all hosts
  hosts: docker
  roles:
    - { role: ansible-roles/install-docker, docker_user: ubuntu }

- name: install and configure jenkins
  hosts: jenkins
  roles:
    - { role: ansible-roles/jenkins, become: true }
    - { role: jenkins-config, tags: ["config"] }
    - { role: tools }

- name: install tomcat
  hosts: nexus
  vars:
    http_port: 8080
    https_port: 8443
    admin_username: admin
    admin_password: adminsecret
  roles:
    - {role: selinux, become: true}
    - {role: tomcat, become: true}
- name: start nexus
  hosts: nexus
  roles:
    - { role: nexus }
